---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: provider-aws
spec:
  resources:
  - kind: BackupBucket
    type: aws
  - kind: BackupEntry
    type: aws
  - kind: ControlPlane
    type: aws
  - kind: Infrastructure
    type: aws
  - kind: Worker
    type: aws
  deployment:
    type: helm
    providerConfig:
      chart: {{ .Values.controllerRegistration.deployment.chart }}
{{- if .Values.controllerRegistration.deployment.values }}
      values:
{{ toYaml .Values.controllerRegistration.deployment.values | indent 8 }}
{{- end }}
