{{- range $i, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $secret.namespace }}
{{- if $secret.labels }}
  labels:
{{ toYaml $secret.labels | indent 4 }}
{{- end }}
type: Opaque
data:
  accessKeyID: {{ b64enc $secret.data.accessKeyID }}
  secretAccessKey: {{ b64enc $secret.data.secretAccessKey }}

---
apiVersion: core.gardener.cloud/v1beta1
kind: SecretBinding
metadata:
  name: {{ $secret.name }}
  namespace: {{ $secret.namespace }}
{{- if $secret.labels }}
  labels:
{{ toYaml $secret.labels | indent 4 }}
{{- end }}
secretRef:
  name: {{ $secret.name }}
{{- end }}
