{{- if .Values.useLegacyProvisioner }}
---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: default
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
    {{- if .Values.managedDefaultClass }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
allowVolumeExpansion: true
provisioner: kubernetes.io/aws-ebs
{{- if semverCompare ">= 1.12-0" .Capabilities.KubeVersion.GitVersion }}
volumeBindingMode: WaitForFirstConsumer
{{- else }}
volumeBindingMode: Immediate
{{- end }}
parameters:
  type: gp2
---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
  name: gp2
allowVolumeExpansion: true
provisioner: kubernetes.io/aws-ebs
{{- if semverCompare ">= 1.12-0" .Capabilities.KubeVersion.GitVersion }}
volumeBindingMode: WaitForFirstConsumer
{{- else }}
volumeBindingMode: Immediate
{{- end }}
parameters:
  type: gp2
{{- end }}
