{{- if not .Values.useLegacyProvisioner }}
---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: gp2
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
{{- end }}
