apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: aws-lb-readvertiser-vpa
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: aws-lb-readvertiser
      minAllowed:
        memory: {{ .Values.resources.requests.memory }}
      controlledValues: RequestsOnly
  targetRef:
    apiVersion: {{ include "deploymentversion" . }}
    kind: Deployment
    name: aws-lb-readvertiser
  updatePolicy:
    updateMode: "Auto"
